export const testimonials = [
  {
    id: 1,
    name: "Sarah M.",
    initials: "SM",
    rating: 5,
    text: "I've been getting the Myers Cocktail every two weeks and the difference in my energy levels is night and day. Dr. Shahzad's team is professional, warm, and the clinic is spotless. Worth every penny.",
    service: "Myers Cocktail",
  },
  {
    id: 2,
    name: "James R.",
    initials: "JR",
    rating: 5,
    text: "Started the semaglutide program in January and I'm down 22 pounds. No gimmicks, no crazy diet plans — just physician supervision and the medication working exactly like it should. This place changed my life.",
    service: "Weight Loss Program",
  },
  {
    id: 3,
    name: "Patricia K.",
    initials: "PK",
    rating: 5,
    text: "Was skeptical about colonics but the staff made me feel completely comfortable. The open-system technology they use is private and dignified. Three sessions in and my digestion has completely transformed.",
    service: "Colonic Hydrotherapy",
  },
  {
    id: 4,
    name: "Michael T.",
    initials: "MT",
    rating: 5,
    text: "BioTE pellets have been a game changer for my energy and mental clarity. Dr. Shahzad took the time to actually explain the science — not just push me through. The follow-up care is exceptional.",
    service: "BioTE Hormone Therapy",
  },
  {
    id: 5,
    name: "Amanda L.",
    initials: "AL",
    rating: 5,
    text: "Three SkinPen sessions and my acne scars from my 20s are almost completely gone. I've spent thousands on other treatments with zero results. IV-LYTES delivered real, visible improvement.",
    service: "SkinPen Microneedling",
  },
  {
    id: 6,
    name: "David C.",
    initials: "DC",
    rating: 5,
    text: "Same-day appointment on a Friday — they fit me in after a brutal week. The Athletic Performance drip had me back on the field feeling 100% by Saturday morning. This is my go-to recovery spot now.",
    service: "IV Hydration",
  },
];
