export const testimonials = [
  {
    id: 1,
    name: "Rachel M.",
    initials: "RM",
    rating: 5,
    text: "Came in completely wiped out after a work trip. Left feeling like myself again. I didn't even know I needed this until I tried it.",
    service: "Myers Cocktail",
    location: "Kingwood, TX",
  },
  {
    id: 2,
    name: "Amanda T.",
    initials: "AT",
    rating: 5,
    text: "My migraines had been bad for two weeks. One migraine drip and it was gone by the time I got to my car. I wish I'd found this place sooner.",
    service: "Migraine Drip",
    location: "Humble, TX",
  },
  {
    id: 3,
    name: "Karen S.",
    initials: "KS",
    rating: 5,
    text: "I've been doing the hormone pellets for 8 months. My energy is back, I'm sleeping better, and I've lost 12 pounds without changing much. Dr. Shahzad actually listens.",
    service: "BioTE Hormone Therapy",
    location: "Kingwood, TX",
  },
  {
    id: 4,
    name: "Marcus B.",
    initials: "MB",
    rating: 5,
    text: "Booked same-day after a rough weekend. The staff was quick, the place is spotless, and I felt the difference within an hour. Worth every penny.",
    service: "Hangover Drip",
    location: "Atascocita, TX",
  },
  {
    id: 5,
    name: "Donna L.",
    initials: "DL",
    rating: 5,
    text: "Started the semaglutide program in January. Down 18 pounds and the side effects were way milder than I expected with Dr. Shahzad monitoring everything.",
    service: "Medical Weight Loss",
    location: "Kingwood, TX",
  },
  {
    id: 6,
    name: "Priya N.",
    initials: "PN",
    rating: 5,
    text: "Three microneedling sessions over 3 months. The acne scars I've had for 10 years are genuinely fading. Clean space, no pushy upsells.",
    service: "SkinPen Microneedling",
    location: "Kingwood, TX",
  },
];
// TODO: Replace with real Google reviews once client provides them
